+incdir+hardware/rtl/soc
+incdir+hardware/rtl/bldc
sim/sys_tb_top.sv
sim/gowin_sim_lib/gw2a/prim_sim.v
fpga/gowin/src/gowin_prom/gowin_prom.v
hardware/rtl/bldc/bldc_clock_divider.v
hardware/rtl/bldc/BLDC_driver.v
hardware/rtl/bldc/bldc_icb_regs.v
hardware/rtl/bldc/bldc_output_compare.v
hardware/rtl/bldc/bldc_rom_sync.v
hardware/rtl/bldc/bldc_sine_phase.v
hardware/rtl/bldc/bldc_sine_pwm.v
hardware/rtl/soc/config.v
hardware/rtl/soc/e203_biu.v
hardware/rtl/soc/e203_clk_ctrl.v
hardware/rtl/soc/e203_clk_unit.v
hardware/rtl/soc/e203_clkgate.v
hardware/rtl/soc/e203_core.v
hardware/rtl/soc/e203_cpu.v
hardware/rtl/soc/e203_cpu_top.v
hardware/rtl/soc/e203_defines.v
hardware/rtl/soc/e203_dtcm_ctrl.v
hardware/rtl/soc/e203_dtcm_ram.v
hardware/rtl/soc/e203_extend_csr.v
hardware/rtl/soc/e203_exu.v
hardware/rtl/soc/e203_exu_alu.v
hardware/rtl/soc/e203_exu_alu_bjp.v
hardware/rtl/soc/e203_exu_alu_csrctrl.v
hardware/rtl/soc/e203_exu_alu_dpath.v
hardware/rtl/soc/e203_exu_alu_lsuagu.v
hardware/rtl/soc/e203_exu_alu_muldiv.v
hardware/rtl/soc/e203_exu_alu_rglr.v
hardware/rtl/soc/e203_exu_branchslv.v
hardware/rtl/soc/e203_exu_commit.v
hardware/rtl/soc/e203_exu_csr.v
hardware/rtl/soc/e203_exu_decode.v
hardware/rtl/soc/e203_exu_disp.v
hardware/rtl/soc/e203_exu_excp.v
hardware/rtl/soc/e203_exu_longpwbck.v
hardware/rtl/soc/e203_exu_oitf.v
hardware/rtl/soc/e203_exu_regfile.v
hardware/rtl/soc/e203_exu_wbck.v
hardware/rtl/soc/e203_ifu.v
hardware/rtl/soc/e203_ifu_ifetch.v
hardware/rtl/soc/e203_ifu_ift2icb.v
hardware/rtl/soc/e203_ifu_litebpu.v
hardware/rtl/soc/e203_ifu_minidec.v
hardware/rtl/soc/e203_irq_sync.v
hardware/rtl/soc/e203_itcm_ctrl.v
hardware/rtl/soc/e203_itcm_ram.v
hardware/rtl/soc/e203_lsu.v
hardware/rtl/soc/e203_lsu_ctrl.v
hardware/rtl/soc/e203_reset_ctrl.v
hardware/rtl/soc/e203_soc_demo.v
hardware/rtl/soc/e203_soc_top.v
hardware/rtl/soc/e203_srams.v
hardware/rtl/soc/e203_subsys_clint.v
hardware/rtl/soc/e203_subsys_gfcm.v
hardware/rtl/soc/e203_subsys_hclkgen.v
hardware/rtl/soc/e203_subsys_hclkgen_rstsync.v
hardware/rtl/soc/e203_subsys_main.v
hardware/rtl/soc/e203_subsys_mems.v
hardware/rtl/soc/e203_subsys_perips.v
hardware/rtl/soc/e203_subsys_plic.v
hardware/rtl/soc/e203_subsys_pll.v
hardware/rtl/soc/e203_subsys_pllclkdiv.v
hardware/rtl/soc/e203_subsys_top.v
hardware/rtl/soc/i2c_master_bit_ctrl.v
hardware/rtl/soc/i2c_master_byte_ctrl.v
hardware/rtl/soc/i2c_master_defines.v
hardware/rtl/soc/i2c_master_top.v
hardware/rtl/soc/sirv_1cyc_sram_ctrl.v
hardware/rtl/soc/sirv_aon.v
hardware/rtl/soc/sirv_aon_lclkgen_regs.v
hardware/rtl/soc/sirv_aon_porrst.v
hardware/rtl/soc/sirv_aon_top.v
hardware/rtl/soc/sirv_aon_wrapper.v
hardware/rtl/soc/sirv_AsyncResetReg.v
hardware/rtl/soc/sirv_AsyncResetRegVec.v
hardware/rtl/soc/sirv_AsyncResetRegVec_1.v
hardware/rtl/soc/sirv_AsyncResetRegVec_129.v
hardware/rtl/soc/sirv_AsyncResetRegVec_36.v
hardware/rtl/soc/sirv_AsyncResetRegVec_67.v
hardware/rtl/soc/sirv_clint.v
hardware/rtl/soc/sirv_clint_top.v
hardware/rtl/soc/sirv_debug_csr.v
hardware/rtl/soc/sirv_debug_module.v
hardware/rtl/soc/sirv_debug_ram.v
hardware/rtl/soc/sirv_debug_rom.v
hardware/rtl/soc/sirv_DeglitchShiftRegister.v
hardware/rtl/soc/sirv_expl_apb_slv.v
hardware/rtl/soc/sirv_expl_axi_slv.v
hardware/rtl/soc/sirv_flash_qspi.v
hardware/rtl/soc/sirv_flash_qspi_top.v
hardware/rtl/soc/sirv_gnrl_bufs.v
hardware/rtl/soc/sirv_gnrl_dffs.v
hardware/rtl/soc/sirv_gnrl_icbs.v
hardware/rtl/soc/sirv_gnrl_ram.v
hardware/rtl/soc/sirv_gnrl_xchecker.v
hardware/rtl/soc/sirv_gpio.v
hardware/rtl/soc/sirv_gpio_top.v
hardware/rtl/soc/sirv_hclkgen_regs.v
hardware/rtl/soc/sirv_icb1to16_bus.v
hardware/rtl/soc/sirv_icb1to2_bus.v
hardware/rtl/soc/sirv_icb1to8_bus.v
hardware/rtl/soc/sirv_jtag_dtm.v
hardware/rtl/soc/sirv_jtaggpioport.v
hardware/rtl/soc/sirv_LevelGateway.v
hardware/rtl/soc/sirv_mrom.v
hardware/rtl/soc/sirv_mrom_top.v
hardware/rtl/soc/sirv_otp_top.v
hardware/rtl/soc/sirv_plic_man.v
hardware/rtl/soc/sirv_plic_top.v
hardware/rtl/soc/sirv_pmu.v
hardware/rtl/soc/sirv_pmu_core.v
hardware/rtl/soc/sirv_pwm16.v
hardware/rtl/soc/sirv_pwm16_core.v
hardware/rtl/soc/sirv_pwm16_top.v
hardware/rtl/soc/sirv_pwm8.v
hardware/rtl/soc/sirv_pwm8_core.v
hardware/rtl/soc/sirv_pwm8_top.v
hardware/rtl/soc/sirv_pwmgpioport.v
hardware/rtl/soc/sirv_qspi_1cs.v
hardware/rtl/soc/sirv_qspi_1cs_top.v
hardware/rtl/soc/sirv_qspi_4cs.v
hardware/rtl/soc/sirv_qspi_4cs_top.v
hardware/rtl/soc/sirv_qspi_arbiter.v
hardware/rtl/soc/sirv_qspi_fifo.v
hardware/rtl/soc/sirv_qspi_media.v
hardware/rtl/soc/sirv_qspi_media_1.v
hardware/rtl/soc/sirv_qspi_media_2.v
hardware/rtl/soc/sirv_qspi_physical.v
hardware/rtl/soc/sirv_qspi_physical_1.v
hardware/rtl/soc/sirv_qspi_physical_2.v
hardware/rtl/soc/sirv_queue.v
hardware/rtl/soc/sirv_queue_1.v
hardware/rtl/soc/sirv_repeater_6.v
hardware/rtl/soc/sirv_ResetCatchAndSync.v
hardware/rtl/soc/sirv_ResetCatchAndSync_2.v
hardware/rtl/soc/sirv_rtc.v
hardware/rtl/soc/sirv_sim_ram.v
hardware/rtl/soc/sirv_spi_flashmap.v
hardware/rtl/soc/sirv_spigpioport.v
hardware/rtl/soc/sirv_spigpioport_1.v
hardware/rtl/soc/sirv_spigpioport_2.v
hardware/rtl/soc/sirv_sram_icb_ctrl.v
hardware/rtl/soc/sirv_tl_repeater_5.v
hardware/rtl/soc/sirv_tlfragmenter_qspi_1.v
hardware/rtl/soc/sirv_tlwidthwidget_qspi.v
hardware/rtl/soc/sirv_uart.v
hardware/rtl/soc/sirv_uart_top.v
hardware/rtl/soc/sirv_uartgpioport.v
hardware/rtl/soc/sirv_uartrx.v
hardware/rtl/soc/sirv_uarttx.v
hardware/rtl/soc/sirv_wdog.v
